[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false
fs_permissions = [{ access = "read-write", path = "./" }]

# Gas reporting
gas_reports = ["*"]

# Additional EVM versions if needed
# evm_version = "london"

# Remappings - clean format
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
]

# RPC endpoints
[rpc_endpoints]
mantle = "https://rpc.mantle.xyz"
mantle_testnet = "https://rpc.testnet.mantle.xyz"
ethereum = "https://eth.llamarpc.com"
goerli = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"

# Etherscan configuration - simple format
[etherscan]
mantle = { key = "${MANTLESCAN_API_KEY}", url = "https://api.mantlescan.xyz/api" }